---

- name: Install Apache Web Server packages
  become: yes
  apt: 
    name: "{{ apache_packages }}"
    state: present
  notify: restart apache

- name: Enable Apache modules
  become: yes
  apache2_module: 
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_enable_modules }}"
  notify: restart apache

# TODO: Add configuration to harden the server (signature off, etc)
