---

- name: Install Apache Web Server packages
  become: yes
  apt: 
    name: "{{ apache_packages }}"
    state: present
  notify: restart apache

- name: Enable Apache modules
  become: yes
  apache2_module: 
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_modules }}"
  notify: restart apache

- name: Register environment variables with Apache
  become: yes
  blockinfile:
    path: /etc/apache2/envvars
    block: ". /home/{{ vm_user }}/.envvars"
  notify: restart apache

# TODO: Add configuration to harden the server (signature off, etc)
