############################
# Configuration variables. #
############################

# Machine
vm_name: "devbox"
vm_hostname: "dev.box"
vm_ram: "2048"
vm_ip: "10.10.10.10"
vm_user: "ubuntu"
vm_group: "www-data"

# Folder mapping
vm_network_type: "nfs"
vm_folder_perm: "u=rwX:g=rwD"
host_path: "~/projects"
guest_path: "/home/ubuntu/projects"
tmp_path: "/home/ubuntu/nfs"

# Git configuration
git_user: ""
git_email: ""
git_rsa_key: "~/.ssh/id_rsa"
git_rsa_key_dest: "~/.ssh/id_rsa"

# Repositories
repositories:
  - { name: github, host: github.com }
  - { name: bitbucket, host: bitbucket.com}

repositories_count: "{{ repositories | length }}"
rebuild_known_hosts: false

# Software stack
config_roles:
  - apache
  - php
  - mysql
  - projects

# Projects

# Projects path
projects_path: "{{ guest_path }}"

# Project parameters
#
#  docroot - string - the location of the project in devbox. It's syntax 
#    contains {{ remote_user }} to make it box indepedent.
#  db_user - string - the name of the database user to be used (empty for root)
#  db_pass - string - the passwrd of the database user to be used (empty for 
#    root)
#  db_name - string - the database name to be used (if empty database is 
#    skipped)
#  tech - string - the technology used in the project (hugo, drupal, symfony)

projects:

  - domain: ""
    project: ""
    docroot: ""
    db_user: ""
    db_pass: ""
    db_name: ""
    tech: ""

## TODO

# Additional packages

# Additional tasks

