############################
# Configuration variables. #
############################

# Machine
vm_name: "devbox"
vm_hostname: "dev.box"
vm_ram: "2048"
vm_ip: "10.10.10.10"
vm_user: "ubuntu"
vm_group: "www-data"

# Folder mapping
vm_network_type: "nfs"
vm_folder_perm: "u=rwX:g=rwD"
host_path: "~/projects"
guest_path: "/home/ubuntu/projects"
tmp_path: "/home/ubuntu/nfs"

# Git configuration
git_user: ""
git_email: ""
git_rsa_key: ""

# Remote user name used in devbox
remote_user: ubuntu

# RSA key location
rsa_key: "~/.ssh/id_rsa"

# Configuration of server stack
#
# Configuration of devbox functionality.
#
# Comment out the parameters that are not needed to ensure that roles are not
# included in the project.
#
config_roles:
  - apache
  - php
  - mysql
  - projects

# Projects root
projects_path: "{{ guest_path }}"

# Projects
# 
# Dictionary to add projects.
# Parameters:
#  domain - string - URL to be used from host machine to access project.
#  docroot - string - the location of the project in devbox. It's syntax 
#    contains {{ remote_user }} to make it box indepedent.
#  db_user - string - the name of the database user to be used (empty for root)
#  db_pass - string - the passwrd of the database user to be used (empty for 
#    root)
#  db_name - string - the database name to be used (if empty database is 
#    skipped)
#  tech - string - the technology used in the project (hugo, drupal, symfony)

projects:

  - domain: ""
    project: ""
    docroot: ""
    db_user: ""
    db_pass: ""
    db_name: ""
    tech: ""

## TODO

# Additional packages
#
# Add additional packages in the variable below to be included in the server,
additional_packages:
  # - uncomment here 

