############################
# Configuration variables. #
############################

# Machine
vm_name: "devbox"
vm_hostname: "dev.box"
vm_cpus: "4"
vm_ram: "2048"
vm_ip: "10.10.10.10"
vm_user: "vagrant"
vm_group: "www-data"

# Folder mapping
vm_network_type: "nfs"
vm_folder_perm: "u=rwX:g=rwD"
host_path: "~/projects"
guest_path: "/home/vagrant/projects"
tmp_path: "/home/vagrant/nfs"

# Git configuration
git_user: ""
git_email: ""
git_rsa_key: "~/.ssh/id_rsa"
git_rsa_key_dest: "~/.ssh/id_rsa"

# Repositories
repositories:
  - { name: github, host: github.com }
  - { name: bitbucket, host: bitbucket.com }

repositories_count: "{{ repositories | length }}"
rebuild_known_hosts: false

# Environment variables
#
# Append to add more
#   name  - string (required) - name of environment variable
#   value - string (required) - value of environment variable

environment_variables:
  - { name: "ENV", value: "local" }

# Software stack
config_roles:
  - nodejs
  - apache
  - php
  - mysql
  - projects

# PHP
php_memory_limit: "1536M"
php_timezone: "Europe/London"
php_xdebug: true
php_laravel: false
php_symfony: false
php_drupal: false
php_wp: false

# Projects

# Projects path
projects_path: "{{ guest_path }}"

# Project parameters
#
#  domain - string (required) - the local domain to access the project
#  path - string (required) - the location of the project
#  docroot - string (required) - the location of docroot within the project
#  type - string (required) - the technology used in the project (generic, hugo, drupal, symfony, wp, laravel)
#  version - string (optional) - the software version required by composer
#  database - string (optional) - the database name to be used
#  repo - string (optional) - a git path to checkout existing projects (uses path)

#projects:

  #- domain: ""
    #path: ""
    #docroot: ""
    #type: ""
    #database: ""
    #repo: ""

## TODO

# Additional packages

# Additional tasks

