############################
# Configuration variables. #
############################

# Machine
vm_name: "devbox"
vm_hostname: "dev.box"
vm_cpus: "4"
vm_ram: "2048"
vm_ip: "10.10.10.10"
vm_user: "vagrant"
vm_group: "www-data"

# Folder mapping
vm_network_type: "nfs"
vm_folder_perm: "u=rwX:g=rwD"
host_path: "~/projects"
guest_path: "/home/vagrant/projects"
tmp_path: "/home/vagrant/nfs"

# Git configuration
git_user: ""
git_email: ""
git_rsa_key: "~/.ssh/id_rsa"
git_rsa_key_dest: "~/.ssh/id_rsa"

# Repositories
repositories:
  - { name: github, host: github.com }
  - { name: bitbucket, host: bitbucket.com}

repositories_count: "{{ repositories | length }}"
rebuild_known_hosts: false

# Software stack
config_roles:
  - nodejs
  - apache
  - php
  - mysql
  - projects

# PHP
php_memory_limit: "1536M"
php_timezone: "Europe/London"
php_xdebug: true
php_laravel: false
php_symfony: false
php_drupal: false
php_wp: false

# Projects

# Projects path
projects_path: "{{ guest_path }}"

# Project parameters
#
#  docroot - string - the location of the project in devbox. It's syntax 
#    contains {{ remote_user }} to make it box indepedent.
#  path - string - the main projects path
#  db_user - string - the name of the database user to be used (empty for root)
#  db_pass - string - the passwrd of the database user to be used (empty for 
#    root)
#  db_name - string - the database name to be used (if empty database is 
#    skipped)
#  tech - string - the technology used in the project (hugo, drupal, symfony)
#  repo - string - git url of the project

#projects:

  #- domain: ""
    #path: ""
    #docroot: ""
    #db_user: ""
    #db_pass: ""
    #db_name: ""
    #tech: ""
    #repo: ""

## TODO

# Additional packages

# Additional tasks

