---

# PHP packages to be installed.
packages_php:
  - php
  - php-cli
  - php-common
  - php-curl
  - php-dev
  - php-fpm
  - php-gd
  - php-zip
  - php-mbstring
  - php-mailparse
  - php-imap
  - php-xdebug

