---

- name: Add NodeSource apt repository key
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install NodeSource apt repository
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_14.x focal main"
    state: present

- name: Install NodeJS packages
  become: yes
  apt:
    name: "{{ packages_node }}"
    state: present

- name: Install NPM packages
  become: yes
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ packages_npm }}"
