---

- name: Check if ~/.my.cnf exists
  stat:
    path: "~/.my.cnf"
  register: mysql_pass

# # Use the code below for debuging.
# - debug:
#     var: mysql_pass.stat.exists

- name: Install MySQL packages
  become: yes
  apt: 
    name: "{{ packages_mysql }}"
    state: present
  notify: restart mysql

- name: Create MySQL root password
  command: /usr/bin/openssl rand -base64 16
  register: mysql_root_pass
  when: not mysql_pass.stat.exists

- name: Update MySQL root password
  become: yes
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_pass.stdout }}"
    state: present
  with_items:
      - 127.0.0.1
      - ::1
      - localhost
  when: not mysql_pass.stat.exists
  notify: restart mysql

- name: Create ~/.my.cnf
  template:
    src: my.cnf.j2
    dest: "~/.my.cnf"
    mode: 0600
  when: not mysql_pass.stat.exists

- name: Add DB environmental variables to .envvars
  blockinfile:
    path: "~/.envvars"
    block: |
      export {{ item.name }}={{ item.value }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  loop:
    - { name: "DB_USER", value: "root" }
    - { name: "DB_PASS", value: "{{ mysql_root_pass.stdout }}" }
  when: not mysql_pass.stat.exists
  notify: restart apache
  
- name: Create Adminer directory
  become: yes
  file:
    path: "/var/www/html/adminer"
    state: directory

- name: Download and install Adminer
  become: yes
  shell: "wget -q -O /var/www/html/adminer/index.php https://github.com/vrana/adminer/releases/download/v4.7.5/adminer-4.7.5-mysql-en.php"
  args:
    creates: "/var/www/html/adminer/index.php"
    warn: false
