---

- name: Create project databases
  mysql_db: 
    name: "{{ item.database }}"
    state: present
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
  with_items:
    - "{{ projects }}"
  when: (item.database is defined) and (item.database != "")
  