---

- name: Install utilities
  become: yes
  apt: 
    name: "{{ packages_utils }}"
    state: present

- name: Update devbox motd
  become: yes
  copy:
    src: "motd"
    dest: "/etc/update-motd.d/00-devbox-motd"
    mode: a+x

- name: Create ~/bin directory
  file:
    path: "~/bin"
    state: directory
    mode: 0775

- name: Create enviromental variables
  file:
    path: "~/.envvars"
    state: touch
    mode: 0700

- name: Add config enviromental variables
  blockinfile:
    path: "~/.envvars"
    block: |
      export {{ item.name }}={{ item.value }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - "{{ environment_variables }}"
  when:
    - environment_variables is defined

- name: Add enviromental variables to .bashrc
  blockinfile:
    path: "~/.bashrc"
    block: |
      # Source environmental variables set by user
      if [ -f ~/.envvars ]; then
        . ~/.envvars
      fi

- name: Add user RSA key
  copy:
    src: "{{ git_rsa_key }}"
    dest: "{{ git_rsa_key_dest }}"
    mode: 0400

- name: Add SSH config
  template:
    src: "ssh_config"
    dest: "~/.ssh/config"
    backup: yes

- name: Add global Git config file
  template:
    src: "gitconfig"
    dest: "~/.gitconfig"

- name: Register number of entries in known_hosts
  shell: "cat ~/.ssh/known_hosts | wc -l"
  register: number_of_known_hosts

- name: Remove known_hosts
  shell: "rm -fr ~/.ssh/known_hosts"
  when: rebuild_known_hosts
  args:
    warn: false

- name: Add RSA fingerprint of repositories to known_hosts
  shell: "ssh-keyscan -H {{ item.host }} >> ~/.ssh/known_hosts"
  with_items:
    - "{{ repositories }}"
  when: rebuild_known_hosts or repositories_count > number_of_known_hosts.stdout
