---

- name: Update apt
  become: yes
  apt: 
    update_cache: yes 
    cache_valid_time: 8400

- name: Install utilities
  become: yes
  apt: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_utils }}"

- name: Update devbox motd
  become: yes
  copy:
    src: "motd"
    dest: "/etc/update-motd.d/00-a_motd_for_devbox"
    mode: a+x

- name: Create ~/bin directory
  file:
    path: "~/bin"
    state: directory
    mode: 0775

- name: Add ~/bin to PATH
  lineinfile:
    dest: "~/.profile"
    regexp: "PATH"
    line: "PATH=\"$HOME/bin:$PATH\""
    backup: yes

- name: Add user RSA key
  copy:
    src: "{{ git_rsa_key }}"
    dest: "{{ git_rsa_key_dest }}"
    mode: 0400

- name: Add SSH config
  template:
    src: "ssh_config"
    dest: "~/.ssh/config"
    backup: yes

- name: Add global Git config file
  template:
    src: "gitconfig"
    dest: "~/.gitconfig"

- name: Register number of entries in known_hosts
  shell: "cat ~/.ssh/known_hosts | wc -l"
  register: number_of_known_hosts

- name: Remove known_hosts
  shell: "rm -fr ~/.ssh/known_hosts"
  when: rebuild_known_hosts
  args:
    warn: false

- name: Add RSA fingerprint of repositories to known_hosts
  shell: "ssh-keyscan -H {{ item.host }} >> ~/.ssh/known_hosts"
  with_items:
    - "{{ repositories }}"
  when: rebuild_known_hosts or repositories_count > number_of_known_hosts.stdout
