---

- name: Update apt
  become: yes
  apt: 
    update_cache: yes 
    cache_valid_time: 8400

- name: Install utilities
  become: yes
  apt: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_utils }}"

- name: Create ~/bin directory
  file:
    path: "~/bin"
    state: directory
    mode: 0775

- name: Add ~/bin to PATH
  lineinfile:
    dest: "~/.profile"
    regexp: "PATH"
    line: "PATH=\"$HOME/bin:$PATH\""
    backup: yes

- name: Add user RSA key
  copy:
    src: "{{ git_rsa_key }}"
    dest: "{{ git_rsa_key_dest }}"
    mode: 0400

- name: Add SSH config
  template:
    src: "ssh_config"
    dest: "~/.ssh/config"
    backup: yes

- name: Add global Git config file
  template:
    src: "gitconfig"
    dest: "~/.gitconfig"

# - name: Read number of known_hosts
#   command: wc -l ~/.ssh/known_hosts
#   register: number_of_known_hosts

# - name: Add RSA fingerprint of repositories to known_hosts
#   shell: "ssh-keyscan -H {{ item.host }} >> ~/.ssh/known_hosts"
#   with_items:
#     - "{{ repositories }}"
#   args:
#     creates: "~/.ssh/known_hosts"
 
