---

- name: Install PHP packages
  become: yes
  apt: 
    name: "{{ packages_php }}"
    state: present
  notify: restart php

- name: Register PHP config path
  shell: "php --ini | grep 'Configuration File (php.ini) Path:' | cut -d ':' -f2 | tr -d ' ' | cut -d '/' -f1-4"
  register: php_config_path

- set_fact:
    php_config_dir: "{{ php_config_path.stdout }}"

- name: Update PHP memory limit
  become: yes
  lineinfile:
    path: "{{ php_config_dir }}/fpm/php.ini"
    regexp: "^memory_limit"
    line: "memory_limit = {{ php_memory_limit }}"
  notify: restart php

- name: Update PHP timezone
  become: yes
  lineinfile:
    path: "{{ php_config_dir }}/fpm/php.ini"
    regexp: "^;date.timezone"
    line: "date.timezone = {{ php_timezone }}"
  notify: restart php

- include: php-composer.yml

- name: Enable xdebug
  include_tasks: php-xdebug.yml
  when: php_xdebug == true

- name: Enable laravel integration
  include_tasks: php-laravel.yml
  when: php_laravel == true
