---

- name: Download and install composer
  shell: "curl -sS https://getcomposer.org/installer | php"
  args:
    creates: "/usr/local/bin/composer"

- name: Move composer to /usr/local/bin
  shell: "sudo mv ~/composer.phar /usr/local/bin/composer"
  args:
    creates: "/usr/local/bin/composer"

- name: Make composer executable
  become: yes
  file: 
    path: "/usr/local/bin/composer"
    mode: a+x
    state: file

